config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :events, except: [:destroy], shallow: true do
    resources :submissions, except: [:index], shallow: true do
      resources :user_role_in_submissions, except: [:index, :show]
      resources :downloads, except: [:index]
    end
    resources :user_role_in_events, except: [:index, :show]
  end
  resources :users, except: [:destroy]
  resources :teams
  get 'homepage/index'

  root 'homepage#index'

end

app/models/event.rb
# Events should never be destroyed
class Event < ActiveRecord::Base
  SUBMISSION_CLOSED = 0
  SUBMISSION_OPEN = 1
  SUBMISSION_ADMIN_ONLY = 2

  # Define status enum
  enum status: {
    draft: 0,
    canceled: 1,
    open_to_public: 2,
    invite_only: 3
  }

  has_many :submissions
  has_many :user_role_in_events
  has_many :users, through: :user_role_in_events

  # These are the requirements in events
  validates :start, presence: true
  validates :end, presence: true
  validates :address, presence: true, length: { minimum: 2 }
  validates :name, presence: true, uniqueness: { scope: [:start, :latitude, :longitude] }
  validates_associated :user_role_in_events

  validates_datetime :start, :on => :create, :after => :today
  validates_datetime :end, :after => :start

  # Handle geo-coding
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  def is_live?
    return (!draft? and !canceled?)
  end

  def Event.submissions_status(event)
    returnStatus = SUBMISSION_CLOSED
    if event.is_live?
      if Time.current.between?(event.start, event.end)
        returnStatus = SUBMISSION_OPEN
      elsif Time.current < event.end
        returnStatus = SUBMISSION_ADMIN_ONLY
      end
    elsif event.is_canceled?
      returnStatus = SUBMISSION_ADMIN_ONLY
    end
    return returnStatus
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authorize_user, only: [:new, :create]
  before_filter :authorize_event_organizer, only: [:edit, :update]
  before_filter :authorize_event_owner, only: [:destroy]
  before_filter :authorize_event_status, only: [:show]
  before_action :set_event, only: [:show, :edit, :update]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @role = nil

    respond_to do |format|
      if @event.save
        # create record of current user's role
        @role = UserRoleInEvent.new
        @role.user_id = current_user.id
        @role.event_id = @event.id
        @role.status = UserRoleInEvent.statuses[:owner]

        if @role.save
          # redirect
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @role.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def can_edit_submission?(event, event_role, submission)
    return_flag = false
    submission_status = Event::submissions_status(event)

    # Make sure we're evaluating a submission, and the status is either opened or closed
    if submission and (submission_status != Event::SUBMISSION_CLOSED)
      if event_role and (event_role.organizer? or event_role.owner?)
        # Event owners and organizers have access to submissions at all times
        return_flag = true
      elsif current_user
        if current_user.admin?
          # Admins have access to submissions at all times
          return_flag = true
        elsif submission.users.include?(current_user) and (submission_status == Event::SUBMISSION_OPEN)
          # Regular users that developed this game has access ONLY if the submission is open
          return_flag = true
        end
      end
    end
    return return_flag
  end
  helper_method :can_edit_submission?

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      # Grab the event instance
      @event = Event.find(params[:id])

      # If the user is logged in, grab its role in the event
      @role = nil
      if current_user
        @role = @event.user_role_in_events.find_by(:user_id => current_user.id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_event_params
      # Require the name start time, end time, whether the submission is open, and status
      params.require(:event).permit(:name, :start, :end, :latitude, :longitude, :address)
    end

    def event_params
      # Require the name start time, end time, whether the submission is open, and status
      params.require(:event).permit(:name, :start, :end, :latitude, :longitude, :address, :description, :submission_grace_period, :submission_open, :header_image, :icon_image, :status)
    end

    def authorize_event_organizer
      if !current_user
        redirect_to '/login'
      elsif !current_user.admin?
        set_event
        unless @role and (@role.owner? or @role.organizer?)
          redirect_to '/'
        end
      end
    end

    def authorize_event_owner
      if !current_user
        redirect_to '/login'
      elsif !current_user.admin?
        set_event
        unless @role and @role.owner?
          redirect_to '/login'
        end
      end
    end

    def authorize_event_status
      set_event
      if @event.draft?
        authorize_event_organizer
      elsif @event.invite_only?
        redirect_to '/login' unless current_user or @role
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attendence.html.erb
<ul>
  <% if current_user %>
    <% if !@role %>
      <li><%= link_to 'RSVP', new_event_user_role_in_event_path(@event) %></li>
    <% elsif @role.owner? %>
      <li><%= link_to 'Add Participant', new_event_user_role_in_event_path(@event) %></li>
    <% else %>
      <li><%= link_to 'Cancel', user_role_in_event_path(@role), method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
  <% else %>
    <li><%= link_to 'Login to RSVP', '/login' %></li>
  <% end %>
  <% for role in @event.user_role_in_events %>
    <li><strong><%= link_to role.associated_username, role.associated_user %></strong> | <%= role.status %>
    <% if @role %>
      <% if role == @role %>
        <% if role.message %>
          | <%= link_to 'Edit Message', edit_user_role_in_event_path(role) %>
        <% else %>
          | <%= link_to 'Add Message', edit_user_role_in_event_path(role) %>
        <% end %>
      <% elsif @role.owner? %>
        | <%= link_to 'Edit Info', edit_user_role_in_event_path(role) %>
      <% end %>
    <% end %>
    <% if role.message %>
      <br/><%= role.message %>
    <% end %>
    </li>
  <% end %>
</ul>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :name_of_location %><br>
    <%= f.text_field :name_of_location %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, Event.statuses.keys %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_submissions.html.erb
<ul>
  <% if @role and !@role.invited? %>
    <li><%= link_to 'Add Submission', new_event_submission_path(@event) %></li>
  <% end %>
  <% for submission in @event.submissions %>
    <li><strong><%= link_to submission.name, submission_path(submission) %></strong> | <%= submission.status %>
    <% if can_edit_submission?(@event, @role, submission) %>
        | <%= link_to 'Edit', edit_submission_path(submission) %>
        | <%= link_to 'Delete', submission_path(submission), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </li>
  <% end %>
</ul>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @event %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start</th>
      <th>End</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.start %></td>
        <td><%= event.end %></td>
        <td><%= event.status %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<p>
  <strong>Attendence:</strong>
  <%= render 'attendence' %>
</p>

<p>
  <strong>Submissions:</strong>
  <% if Event::submissions_status(@event) == Event::SUBMISSION_CLOSED %>
    <ul>
      <li>Submission will not open until <%= @event.start %>.</li>
      <li>It is still <%= Time.current %>.</li>
    </ul>
  <% else %>
    <%= render 'submissions' %>
  <% end %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@event.latitude},#{@event.longitude}&markers=#{@event.latitude},#{@event.longitude}&zoom=18&size=640x400",
              class: 'img-fluid img-rounded', alt: "#{@event.address} on the map"%>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', :back %>