config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :events, except: [:destroy], shallow: true do
    resources :submissions, except: [:index], shallow: true do
      resources :user_role_in_submissions, except: [:index, :show]
      resources :downloads, except: [:index]
    end
    resources :user_role_in_events, except: [:index, :show]
  end
  resources :users, except: [:destroy]
  resources :teams
  get 'homepage/index'

  root 'homepage#index'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  # Define status enum
  enum status: {
    draft: 0,
    visible_to_public: 1,
    visible_to_attendees_only: 2,
    visible_to_judges_only: 3
  }

  # Indicate a submission must belong to an event
  belongs_to :event

  has_many :downloads, dependent: :destroy
  has_many :user_role_in_submissions, dependent: :destroy
  has_many :team_role_in_submissions, dependent: :destroy
  has_many :users, through: :user_role_in_submissions
  has_many :teams, through: :team_role_in_submissions

  # These are the requirements in teams
  validates :name, presence: true, uniqueness: { scope: [:event_id] }, length: { minimum: 2 }
  validates_associated :event, :user_role_in_submissions
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  # FIXME: only allow the owner, event organizer, or admin to destroy a submission
  before_filter :authorize_user, only: [:edit, :update, :destroy, :new, :create]
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    # Grab the event instance
    @event = Event.find(params[:event_id])
    @submission = Submission.new(:event_id => @event.id)
    @submission_form = [@event, @submission]
  end

  # GET /submissions/1/edit
  def edit
    @submission_form = @submission
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    # Grab the event instance
    @event = Event.find(params[:event_id])
    @submission.event_id = @event.id

    respond_to do |format|
      if @submission.save

        # create record of current user's role
        @role = UserRoleInSubmission.new
        @role.user_id = current_user.id
        @role.submission_id = @submission.id
        @role.status = UserRoleInSubmission.statuses[:owner]

        # Save this role
        if @role.save
          # redirect
          format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
          format.json { render :show, status: :created, location: @submission }
        else
          format.html { render :new }
          format.json { render json: @role.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to @event, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      # Grab submission instance
      @submission = Submission.find(params[:id])

      # Grab the event instance
      @event = @submission.event

      # If the user is logged in, grab its role in the event
      @role = nil
      if current_user
        @role = @submission.user_role_in_submissions.find_by(:user_id => current_user.id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:name, :description, :status)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_downloads.html.erb
<ul>
  <% if current_user and @role %>
    <li><%= link_to 'Add a downloadable', new_submission_download_path(@submission) %></li>
  <% end %>
  <% for download in @submission.downloads %>
    <li><strong>
    <% if download.file and !download.file.blank? %>
      <%= link_to download.name, download.file.url %>
    <% elsif download.link and !download.link.blank? %>
      <%= link_to download.name, download.link %>
    <% else %>
      <%= download.name %>
    <% end %>
    </strong>

    <% if download.file_fingerprint and !download.file_fingerprint.blank? %>
      <br/>MD5: <%= download.file_fingerprint %>
    <% end %>

    <% if download.platforms and !download.platforms.blank? %>
      <br/>Supports: <%= download.platforms %>
    <% end %>

    <br/><%= link_to 'More Info', download_path(download) %>
    <% if current_user and @role %>
      | <%= link_to 'Edit', edit_download_path(download) %>
      | <%= link_to 'Delete', download_path(download), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </li>
  <% end %>
</ul>

app/views/submissions/_form.html.erb
<%= form_for(@submission_form) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.select :status, Submission.statuses.keys %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/_roles.html.erb
<ul>
  <% if current_user and @role and @role.owner? %>
    <li><%= link_to 'Add Contributor', new_submission_user_role_in_submission_path(@submission) %></li>
  <% end %>
  <% for role in @submission.user_role_in_submissions %>
    <li><strong><%= link_to role.associated_username, role.associated_user %></strong> | <%= role.status %>
    <% if @role %>
      <% if role == @role %>
        <% if role.role %>
          | <%= link_to 'Edit Message', edit_user_role_in_submission_path(role) %>
        <% else %>
          | <%= link_to 'Add Message', edit_user_role_in_submission_path(role) %>
        <% end %>
      <% elsif @role.owner? %>
        | <%= link_to 'Edit Info', edit_user_role_in_submission_path(role) %>
      <% end %>
    <% end %>
    <% if role.role %>
      <br/><%= role.role %>
    <% end %>
    </li>
  <% end %>
</ul>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @submission %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Submissions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Header image</th>
      <th>Icon image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.name %></td>
        <td><%= submission.description %></td>
        <td><%= submission.header_image %></td>
        <td><%= submission.icon_image %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %> |
<%= link_to 'Back', :back %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Submission For:</strong>
  <%= link_to @event.name, @event %>
</p>

<p>
  <strong>Name:</strong>
  <%= @submission.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @submission.description %>
</p>

<p>
  <strong>Downloads:</strong>
  <%= render 'downloads' %>
</p>

<p>
  <strong>Submitted By:</strong>
  <%= render 'roles' %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Delete', submission_path(@submission), method: :delete, data: { confirm: 'Are you sure?' } %>